SET WEBDIR=%1
SET JACOCO_REPORT=%2
SET HTML_DIR=%2
SET CLASSFILES=%WEBDIR%\WEB-INF\classes
SET SOURCEFILES=%WEBDIR%\WEB_INF\src
SET JACOCO_HOME=%CATALINA_HOME%\jacoco
SET JACOCO_JAR=%JACOCO_HOME%\jacococli.jar

ECHO CATALINA_HOME = %CATALINA_HOME%
ECHO java -jar %JACOCO_JAR% report %ACOCO_REPORT% --sourcefiles %SOURCEFILES% --classfiles %CLASSFILES% --html %HTML_DIR%
java -jar %JACOCO_JAR% report %ACOCO_REPORT% --sourcefiles %SOURCEFILES% --classfiles %CLASSFILES% --html %HTML_DIR%